# Generated by Django 3.0.8 on 2021-05-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210504_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is Archived?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_owner',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Who (Defaults to Me)'),
        ),
    ]
