# Generated by Django 3.0.8 on 2021-05-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210527_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='goal_name',
            field=models.CharField(max_length=512, verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(verbose_name='Action'),
        ),
    ]
